version: '3.2'
services:
  brandr-api:
    container_name: brandr-api
    image: scienta/brandr-api:branch-master
    working_dir: /app
    ports:
      - "${BIND_INTERFACE}:1337:3000"
    environment:
      - NODE_ENV=dev
      - API_ENDPOINT=${API_ENDPOINT}
      - DEBUG=*,-navigator:info,-sequelize*,-koa*,-nodemon*,-snapdragon*,-puppeteer*
    command: nodemon /app/index.js
