version: '3'
services:
  node:
    container_name: logo-extractor
    image: scienta/logo-extractor:master
    volumes:
      - ./app:/app
      - ./test:/test
      - ./app/node_modules:/app/node_modules
      - ./app/node_modules:ro:/app/resources/hosts-blocklist
    ports:
      - "${BIND_INTERFACE}:1337:3000"
    environment:
      - NODE_ENV=dev
      - DEBUG=*,-sequelize*,-koa*,-nodemon*,-snapdragon*,-puppeteer*
    command: nodemon /app/index.js #tail -f /dev/null
