version: '3'
services:
  node:
    container_name: logo-extractor
    image: scienta/logo-extractor:master
    volumes:
      - ./app:/usr/src/app
      - ./test:/test
      - ./app/node_modules:/app/node_modules
    ports:
      - "${BIND_INTERFACE}:1337:80"
    environment:
      - NODE_ENV=dev
    command: nodemon /usr/src/app/index.js
