version: '3'
services:
  node:
    container_name: logo-extractor
    image: scienta/logo-extractor:master
    volumes:
      - ./app:/app
      - ./test:/test
      - ./app/node_modules:/app/node_modules
    ports:
      - "${BIND_INTERFACE}:1337:3000"
    environment:
      - NODE_ENV=dev
    #entrypoint: docker-node-entrypoint #nodemon /app/index.js
    command: nodemon /app/index.js #tail -f /dev/null
