version: '3'
services:
  node:
    container_name: logo-extractor
    image: scienta/logo-extractor:master
    volumes:
      - ./app:/app
      - ./output:/output
      - ./app/node_modules:/app/node_modules
      - /app/resources/hosts-blocklist
    ports:
      - "${BIND_INTERFACE}:1337:3000"
    environment:
      - NODE_ENV=dev
      - APP_HOST=http://${BIND_INTERFACE}:1337
      - DEBUG=*,-navigator:info,-sequelize*,-koa*,-nodemon*,-snapdragon*,-puppeteer*
    command: nodemon /app/index.js
